"""Add new case fields: client details, opposite party, party type, remarks

Revision ID: a894f0248bef
Revises: 0f333ba2f1f1
Create Date: 2025-12-27 23:21:47.461987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a894f0248bef'
down_revision = '0f333ba2f1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('client_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('opposite_party', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('otherside_counsel', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('party_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.alter_column('client_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('remarks')
        batch_op.drop_column('party_type')
        batch_op.drop_column('otherside_counsel')
        batch_op.drop_column('opposite_party')
        batch_op.drop_column('client_phone')
        batch_op.drop_column('client_address')
        batch_op.drop_column('client_name')

    # ### end Alembic commands ###
